apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
  labels:
    app: node-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-mongo

  template:
    metadata:
      labels:
        app: node-mongo
    spec:
      containers:
        - name: node-mongo
          image: mandipkaur/nagp-node-app:04
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT
