apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-mongo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-mongo
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
